---
title: "STAT112 Project"
author: "Jenny Li, Geven Liu, Wenxuan Zhu"
date: '2022-04-16'
output: html_document
---
```{r}
library(tidyverse)
library(lubridate)
library(ggthemes) 
library(geofacet)
library(openintro)
library(gplots)
library(RColorBrewer)
library(ggthemes)     
library(plotly) 
library(gganimate)
library(gifski) 
library(transformr) 
library(patchwork) 

Employee <- read.csv('Employee.csv')

```


# Monthly Income Histogram

```{r, fig.alt= "The monthly income distributions in the dataset using a density plot with the blue line showing the mean monthly income for all workers" }
 Employee %>% 
  ggplot(aes(x = MonthlyIncome)) +
  geom_histogram(aes(y=..density..), color = "#E95C20FF", fill = "#F0B67F", bins = 40) +
  geom_vline(aes(xintercept = mean(MonthlyIncome)), color = "#4F2C1DFF", size = 1.5) +
  geom_density(alpha=.5, fill="#006747FF") + 
  labs(title = "Monthly Income Distributions", 
       subtitle = "Histogram Plot",
       x = NULL,
       y = NULL)
```

# Monthly Income by department (boxplot)

```{r}
 Employee %>% 
  ggplot(aes(x = MonthlyIncome, color = Gender)) +
  geom_boxplot(alpha = 0.2 ) +
  geom_vline(aes(xintercept = mean(MonthlyIncome)), color = "#4F2C1DFF", size = 1) +
  facet_wrap(vars (Department)) + 
  scale_color_manual(values = c("Female" = "#E95C20FF",
                                "Male"="#006747FF")) + 
  labs(title = "Monthly Income Distributions by department", 
       subtitle = "Histogram Plot",
       x = NULL,
       y = NULL)
```


# Average income vs total working years by department

```{r}
Employee %>%
  group_by(Department,TotalWorkingYears,Attrition) %>%
  summarize(`Average income` = mean(MonthlyIncome)) %>%
  ggplot(aes(x=TotalWorkingYears)) +
  geom_point(size=1,
            aes( y=`Average income`,
            color=Attrition))+
  geom_smooth(aes(y=`Average income`,
             color=Attrition),
             se = FALSE,n=30,size=0.7)+
  facet_wrap(~Department)+
  theme_classic()+
  labs(x='Total working years')
```

